version: 1
formatters:
  default:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
  simple:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  console_simple:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: '../log/log.txt'
    formatter: default
loggers:
  console_logger:
    level: DEBUG
    handlers: [console]
    propagate: False
  console_simple_logger:
    level: DEBUG
    handlers: [console_simple]
    propagate: False
  file_logger:
    level: DEBUG
    handlers: [file]
    propagate: False
disable_existing_loggers: True